### ISSUE TITLE
zsm show compression rate option

### ISSUE THREAD

**Issue by axet** [VR-25/zram-swap-manager#12]
zsm does not have an option to show actual compression rate and total size.

easy to obtain:

/sys/devices/virtual/block/zram0/compr_data_size
/sys/devices/virtual/block/zram0/orig_data_size
/sys/devices/virtual/block/zram0/mem_used_total

https://docs.kernel.org/admin-guide/blockdev/zram.html

**Comment by VR-25** [comment]
Not all kernels have these.

Anyway, I made some changes.
If you use Termux, I recommend trying `sudo zsm -e`.
You'll need the `tsu` and `zramctl` packages.
