### ISSUE TITLE
Provide update.json for module updates within magisk app

### ISSUE THREAD

**Issue by ClockGen** [VR-25/zram-swap-manager#13]
Hello, magisk supports module updates from within the app itself, if the module has proper fields in module.prop and appropriate update.json file upstream (see https://topjohnwu.github.io/Magisk/guides.html). Could you provide these?

**Comment by IzzySoft** [comment]
Guess you can mark this "solved", @ClockGen: the `update.json` is named [`module.json`](https://github.com/VR-25/zram-swap-manager/blob/master/module.json) here (so at least [my Magisk repo](https://apt.izzysoft.de/magisk) can handle that), and the proper fields in [`module.prop`](https://github.com/VR-25/zram-swap-manager/blob/master/module.prop) seem to be present.

Issue still remains: the ZIP contains an invalid `module.prop`:

```ini
author=VR25
description=
domain=vr25
id=zram-swap-manager
name=zRAM Swap Manager
version=
versionCode=
```

Values for description, version and versionCode are missing, resulting in an

```
Pull ERROR: _from_zip_common: [zram-swap-manager] -> ValueError(invalid literal for int() with base 10: '')
```

when `versionCode` is being evaluated.

**Comment by VR-25** [comment]
Done.

**Comment by IzzySoft** [comment]
```json
"zipUrl": "https://github.com/VR-25/zram-swap-manager/releases/download/v2024.12.15/zsm_android_2024-12-15_10.30.42.zip"
```

The real url is `https://github.com/VR-25/zram-swap-manager/releases/download/v2024.10.15/zsm_android_2024-12-15_10.30.42.zip` – tag name does not match what you have in `module.json`. Guess a typo when creating the tag (`v2024.10.15` was supposed to be `v2024.12.15`)?

**Comment by VR-25** [comment]
> ```json
> "zipUrl": "https://github.com/VR-25/zram-swap-manager/releases/download/v2024.12.15/zsm_android_2024-12-15_10.30.42.zip"
> ```
> 
> The real url is `https://github.com/VR-25/zram-swap-manager/releases/download/v2024.10.15/zsm_android_2024-12-15_10.30.42.zip` – tag name does not match what you have in `module.json`. Guess a typo when creating the tag (`v2024.10.15` was supposed to be `v2024.12.15`)?

Aw, snap!

Fixed. Thanks!

https://github.com/VR-25/zram-swap-manager/releases/tag/v2024.12.15.1

**Comment by IzzySoft** [comment]
Thanks! Online in the FOSS Magisk repo at IzzyOnDroid now: https://apt.izzysoft.de/magisk
