### ISSUE TITLE
Is this module compatible with Android 14 QPR2?

### ISSUE THREAD

**Issue by DeepBlueBubble** [VR-25/zram-swap-manager#16]
Hi.
One zram module that I used bricked my phone, so I am not dare to try this one to see it's compatibility. If someone can answer me, then I will be appreciated

**Comment by fluoriteByte** [comment]
You can probably check if it works if you a magisk module to rescue you if the phone bootloops, try installing Anti Bootloop from the magisk-modules-alt-repo repo

**Comment by VR-25** [comment]
I use it on Android 14 and just released a new version.
