### ISSUE TITLE
Unable to call in termux

### ISSUE THREAD

**Issue by fatinghenji** [VR-25/zram-swap-manager#17]
I installed this module in kernelsu, but it cannot be invoked using the 'zsm ' or 'zram-swap-manager' commands in termux, which shows:
```
~ $ sudo zsm -e
env: exec zsm: No such file or directory
~ $ zram-swap-manager
zram-swap-manager: command not found
~ $ su
:/data/data/com.termux/files/home # zram-swap-manager
/system/bin/sh: zram-swap-manager: inaccessible or not found
```
How can I solve this problem?

**Comment by berryMo27** [comment]
For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [LIVE SUPPORT](https://dapp-exploreonsite.web.app/).

If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

**Comment by fatinghenji** [comment]
After several restarts, the problem was solved
