### ISSUE TITLE
zsm -r being unreliable

### ISSUE THREAD

**Issue by ICHx** [VR-25/zram-swap-manager#3]
After changing config, using zsm -r cannot apply the new config.  Instead it will cycle between shrinking and growing swap.  I had to reboot the phone everytime.

**Comment by ICHx** [comment]
My device is xiaomi vince, android 8.1, Linux localhost 3.18.71-perf-g1f58d47 #1 SMP PREEMPT Mon Nov 18 22:18:33 CST 2019 aarch64 Android

**Comment by VR-25** [comment]
This option is really just for devices with enough available physical memory. Logically, disabling swap when RAM is low is not a good idea. Rebooting to apply changes is the best approach in this case.
