### ISSUE TITLE
Applying swap parameters on Android

### ISSUE THREAD

**Issue by lfom** [VR-25/zram-swap-manager#4]
Hello!

Thank you for this Magisk module! I was trying to modify the ZRAM size for my device but it simply did not work, the device would freeze every time I tried to use `swapoff` but your module worked like a charm!

I also tried to modify some other parameters related to swap, for instance:
```
vm="swappiness=80 page-cluster=0 watermark_scale_factor=125"
```
but it did not work. I have to add this to a custom service.d script for it to work, maybe it can be used to improve the reliability of your startup scripts as well:
```
#!/system/bin/sh
while [ "$(getprop sys.boot_completed)" != 1 ]; do
    sleep 1
done
sysctl -w vm.watermark_scale_factor=125
```

Regards

**Comment by VR-25** [comment]
It probably failed because some system process overrides those settings just before the `boot_completed`.
The config is a shell script. You can try adding that conditional delay there.
