### ISSUE TITLE
Please advise on how to write the configuration file

### ISSUE THREAD

**Issue by QQ1071378751** [VR-25/zram-swap-manager#6]
Is this configuration item  `mem_percent=33 # [33], memory limit·` the option to control the size of zram?
I'm having problems modifying this option, for example, if I set 33%, the actual memory allocated is about 66% RAM.
My phone has 6G RAM, is the phone you are using for development the 12G RAM version?
Can you tell me the function of this configuration item,  `vm="swappiness=80 page-cluster=0· 
What is the function of  ·vm="swappiness=80"` ?

Will modifying this  `/sys/module/lowmemorykiller/parameters/minfree`
 file will change the phone's memory recycling policy?
My phone kills memory when 1GB of memory is left after zRAM is turned off, which leads to underutilized memory, I think it is more appropriate to kill memory when 256MB is left.

**Comment by QQ1071378751** [comment]
thank you

**Comment by yeezylife** [comment]
still don't know how to control the size of zram. anyone got the answer now?
