### ISSUE TITLE
Kernelsu Support

### ISSUE THREAD

**Issue by Theo-user** [VR-25/zram-swap-manager#7]
Can we have support for KernelSU

**Comment by VR-25** [comment]
Working on it.

**Comment by VR-25** [comment]
[zsm_android_2023-07-16_15:07:08.zip](https://github.com/VR-25/zram-swap-manager/files/12064241/zsm_android_2023-07-16_15.07.08.zip)
Try this build.

**Comment by Mylinde** [comment]
Works. 👍
